packages:
  - 'packages/*'

overrides:
  handlebars: ^4.7.9
  tar: ^7.5.7
  '@xmldom/xmldom': ^0.8.13
  follow-redirects: ^1.16.0
  fast-xml-parser: ^5.7.0
  serialize-javascript: ^7.0.5
  semver: '>=5.7.2'
  picomatch@2: ^2.3.2
  picomatch@4: ^4.0.4
  brace-expansion@1: ^1.1.13
  brace-expansion@2: ^2.0.3
  '@isaacs/brace-expansion': ^5.0.1
  bn.js@4: ^4.12.3
  bn.js@5: ^5.2.3
  bl: ^1.2.3
  minimatch@3: 3.1.4
  minimatch@5: 5.1.8
  minimatch@9: 9.0.7
  minimatch@10: 10.2.3
  lodash: '>=4.18.0'
  rollup: ^4.59.0
  axios: '>=1.15.0'
